# Generated by Django 5.2.1 on 2025-08-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='bith_date',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='autor',
            new_name='author',
        ),
    ]
