# Generated by Django 5.2.1 on 2025-08-10 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0007_recommendation_book_recommended_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='recommendation',
            old_name='created_at',
            new_name='recommended_at',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterUniqueTogether(
            name='recommendation',
            unique_together={('user', 'book')},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='recommended_by',
            field=models.ManyToManyField(related_name='recommendations', through='minilibrary.Recommendation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='language',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='minilibrary.book'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='reason',
        ),
    ]
